services:
  backend:
    build: ./backend
    container_name: ureg_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=production

  frontend:
    build: ./frontend
    container_name: ureg_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
